package Tutorial;

import org.testng.annotations.Test;

public class Exception_Test {

	@Test(expectedExceptions= {ArithmeticException.class})
	public void exp1()
	{
	
		System.out.println(2/0);
		
	}
	
	
	@Test(expectedExceptions= {StringIndexOutOfBoundsException.class})
	public void exp2()
	{
		
		String name="Dhoni";
		
		System.out.println(name.charAt(10)); 
		
	}
	
	@Test(expectedExceptions= {Exception.class})
	public void exp3()
	{
		
	int a[]= {1,2};
		
		System.out.println(a[10]); 
		
	}
	
}
